name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: ðŸ¦€ Run Rust tests
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ›Žï¸ Checkout repository
        uses: actions/checkout@v4

      - name: ðŸ¦€ Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: ðŸ“¦ Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov

      - name: ðŸ§ª Run tests with coverage
        run: |
          cargo llvm-cov --lcov --output-path lcov.info

      - name: ðŸ”§ Normalize coverage paths
        run: |
          sed -i 's|SF:.*/src/|SF:src/|' lcov.info
          echo "âœ… Normalized paths in lcov.info"
          head -n 10 lcov.info

#      - name: ðŸ”§ Normalize coverage paths
#        run: |
#          sed -i '' 's|SF:.*/src/|SF:src/|' lcov.info
#          echo "âœ… Normalized paths in lcov.info"
#          head -n 10 lcov.info

      - name: ðŸ” Run SonarCloud analysis
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.projectVersion=${{ github.run_number }}
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}